### PR TITLE
Need Help!!!

### PR DESCRIPTION
**Pull request by dddora**
I have an issue about the "set image" button like to Textinput image URL...
Could you guys help me up?
Thanks!

### CODE REVIEW

**Comment by NicolasAsis** [comment]
Try to make a const for 'backgroundImage'...
This would look like:
const [backimg, setBackimg] = useState();

You can make the background image in your styles equal to that const...

Figure out a way to get the value in the text input and put it into that variable...Hope this helps!

**Comment by NicolasAsis** [comment]
backgroundImage = {backimg}...something like this

**Comment by NicolasAsis** [comment]
https://facebook.github.io/react-native/docs/imagebackground

**Review by NicolasAsis — APPROVED** [review]

**Review by nicoleli11 — APPROVED** [review]
goooood jobbbbb!

**Pull request merged**
